// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy5BN2K-yBv7GkqP0n3JF5V82XW2V2u1E',
    appId: '1:471788972864:web:41dae58dfdbb18ca1568a5',
    messagingSenderId: '471788972864',
    projectId: 'waiapp-4edaf',
    authDomain: 'waiapp-4edaf.firebaseapp.com',
    storageBucket: 'waiapp-4edaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ZGxD0GEiQTTK_JVsXO_c7b7GWO6Mql8',
    appId: '1:471788972864:android:2be4fd35d43e144a1568a5',
    messagingSenderId: '471788972864',
    projectId: 'waiapp-4edaf',
    storageBucket: 'waiapp-4edaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfgbyRneWK91zS2IKzOdPliKtIGRXbSXk',
    appId: '1:471788972864:ios:40becde1918cab5f1568a5',
    messagingSenderId: '471788972864',
    projectId: 'waiapp-4edaf',
    storageBucket: 'waiapp-4edaf.firebasestorage.app',
    iosBundleId: 'com.example.waiLifeAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfgbyRneWK91zS2IKzOdPliKtIGRXbSXk',
    appId: '1:471788972864:ios:40becde1918cab5f1568a5',
    messagingSenderId: '471788972864',
    projectId: 'waiapp-4edaf',
    storageBucket: 'waiapp-4edaf.firebasestorage.app',
    iosBundleId: 'com.example.waiLifeAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy5BN2K-yBv7GkqP0n3JF5V82XW2V2u1E',
    appId: '1:471788972864:web:eee3ed71d8b762791568a5',
    messagingSenderId: '471788972864',
    projectId: 'waiapp-4edaf',
    authDomain: 'waiapp-4edaf.firebaseapp.com',
    storageBucket: 'waiapp-4edaf.firebasestorage.app',
  );
}
