// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2IDw9ZYDFsQUhiYmpWCu6VRBsYgOZqg4',
    appId: '1:793319730662:web:a7a7a5673977e5bb15fa27',
    messagingSenderId: '793319730662',
    projectId: 'riyashome-863ea',
    authDomain: 'riyashome-863ea.firebaseapp.com',
    storageBucket: 'riyashome-863ea.firebasestorage.app',
    measurementId: 'G-90FTJ2DVVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1RHH8lt5odK5nA6-wiiK0E24PD6bnbh4',
    appId: '1:793319730662:android:35544556ec68c22915fa27',
    messagingSenderId: '793319730662',
    projectId: 'riyashome-863ea',
    storageBucket: 'riyashome-863ea.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrC0n2sZ7MdMBG_BGOwEzXXEB5IRfyxCQ',
    appId: '1:793319730662:ios:4a916d670aab41be15fa27',
    messagingSenderId: '793319730662',
    projectId: 'riyashome-863ea',
    storageBucket: 'riyashome-863ea.firebasestorage.app',
    iosBundleId: 'com.example.waiLifeAssistant',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrC0n2sZ7MdMBG_BGOwEzXXEB5IRfyxCQ',
    appId: '1:793319730662:ios:4a916d670aab41be15fa27',
    messagingSenderId: '793319730662',
    projectId: 'riyashome-863ea',
    storageBucket: 'riyashome-863ea.firebasestorage.app',
    iosBundleId: 'com.example.waiLifeAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2IDw9ZYDFsQUhiYmpWCu6VRBsYgOZqg4',
    appId: '1:793319730662:web:bcd09bc4eb5674a215fa27',
    messagingSenderId: '793319730662',
    projectId: 'riyashome-863ea',
    authDomain: 'riyashome-863ea.firebaseapp.com',
    storageBucket: 'riyashome-863ea.firebasestorage.app',
    measurementId: 'G-GG3DF5LSXQ',
  );
}
